### ISSUE TITLE
SelectAddress

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#16]
A component for user to select billing / shipping addresses
It is assumed to be use with Formik.  It's a warper on `MultiSelect`, that fetch address list from backend and provide to MultiSelect.
Also provide convenience to users to add address on the spot.
Assume user has logined.

## URL
`./src/component/SelectAddress.js`

## Props List
- [x] `allowAddAddress`: boolean, if true, show a button that when click, show a modal with `addNewAddressForm` #17 , let user input address and save.  If not provided default to `false`

- [x] `account_id`: pass to `addNewAddressForm` #17  as props

- [x] `placeholder`: phrase to show in dropdown box when nothing is selected.  pass to `MultiSelect` directly.

- [x] `onChange`: callback when address changed.  If using Formik should give it `setFieldValue`

- [x] `onAddNewAddress`: callback when a new address is added.  Only useful if `allowAddAddress` is true.  If using Formik with Apollo, default should give it `refetch()`

- [x] `value`: The selected address's `_id`.  If `multiSelect` is true, provide in array, else provide as String.

## Spec

- [x] This component should use `MultiSelect`(./src/component/Formik-MultiSelect.js) , by passing the address list to `MultiSelect` as props.option

- [x] fetch addressList from backend using GraphQL query `getMyAccount`  #31

- [x] After fetch, inject a `value` key for each object in array `address_id`.  set value = `_id` of the object.  (So MultiSelect can auto pick up and return _id)

- [x] Also show a "add new address" button if `props.allowAddAddress` is true

- [x] "Add New Address" should build a new button using styled-component within this .js file.  Just basic style it is ok.

- [x] When clicked "Add New Address" , should a modal (./src/component/modal.js), and inside modal show `addNewAddressForm` #17 

- [x] Pass along all necessary props to addNewAddressForm, including a function for `onSubmit`  When this function is called, re-fetch the GraphQL query #31

**Comment by strahinjarepo** [comment]
on 4th issue, "Also show a 'add new address' button if props.allowAddAddress' is true"
"this.state.showAddNewAddressModal" is state variable to visibility of modal, add address button

**Comment by screw123** [comment]
Added in props:
defaultValue
onChange
onAddNewAddress
