### ISSUE TITLE
addNewAddressForm

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#17]
A form to add a new address for an account
Assume user has logined.  Parents have to make sure of this.

## URL
./src/form/addNewAddressForm.js

## Props List

- [x] account_id: submit together with user inputs to backend

- [x] onSubmit: get a function from parent, return the Address Object that returns from GraphQL mutation

## Spec

- [x] Overall code pattern may refer `SignUpForm` (./src/form/SignUpForm.js) for quick start.

- [x] Assume user is logined.  Get user_id from `GqlApi` #24,  `GqlApi.state.myself._id`

- [x] on submit, use `GqlApi.getGqlClient()` to submit to mutation `addAddress` #18 

- [x] Appropriate error checking for `validate` prop of `Formik`

- [x] Fields to include: 1. `addressType`: Hard-code to "CUSTOMER" for now

- [x] 2. `legalName`: String max 255 characters.  Let user input address name.  This will also be print on invoice later.  Cannot be empty
"
- [x] 3. `addressCountry`: Let user choose among "KOWLOON", "HONG KONG ISLAND", "NEW TERRITORIES", "LANTAU".  Cannot be empty.  Use `MultiSelect` #15 

- [x] 4. `addressRegion1`: String max 50 characters.

- [x] 5. `addressRegion2`: String max 50 characters.  _Will change later to provide a list for users to choose from_

- [x] 6. `streetAddress`: String 5-500 chars

- [x] 7. `telephone`: Any 8 chars long all numbers.  Cannot be empty

- [x] 8. `account_id`: = this.props.account_id

- [x] When submit failed, parse Error using `parseErr` and show to user (./util/parseErr.js)

- [x] When submit is successful, call `props.onSubmitSuccess` with the address returned by backend as parameter, it should be `props.onSubmitSuccess(data.addAddress)` but please check and make sure.

## TBC 

- redefine spec for `addressRegion2`
- render and submit without <form>?  Alternatively get a way to render outside of form.
