### ISSUE TITLE
SalesOrderConfirmForm

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#19]
Getting a quotation from backend and present it to user.
Also ask for billing address from user and submit to backend together, to create sales order.
Assume user has logined.  Parents have to make sure of this.

## URL
./src/form/SalesOrderConfirmForm.js

## Props List

- [ ] `account_id`: required to retrieve quotation from backend

- [ ] `quotation_id`: required to retrieve quotation from backend

- [ ] `onSubmit`: optional.  If provided will call this prop with the returned SalesOrder from backend.

## Spec

- [ ] Using `props.quotation_id` and `props.account_id`, query `getQuotationById` on backend using `GqlApi.getGqlClient()`

- [ ] Create a styled component for each item in quotation and reasonably render them (everything received in the quotation object returned from backend)

- [ ] before showing the quotation, show `SelectAddress` #16 and pass necessary props to it.  (FYI, `getQuotationById` query will return both `getQuotationById` and `getAccountById`, with `getAccountById`, addresses are within `address_id`.  please check the return by yourself)

- [ ] `SelectAddress` should, by default, have `defaultBillingAddress_id ` selected by default.  Also supply all necessary props #16 

- [ ] _If `account` does not have `stripeCustomerObject`, show `StripeUI`

- [ ] Ask user to confirm at bottom of the form by giving `Submit` button (use Formik `FormButton` in `./src/component/Formik-Basic.js`

- [ ] Submit to backend using mutation `addRentalOrder`, and call `props.onSubmit` if it is defined.  _If StripeUI` is present, create customer object before addRentalOrder_

- [ ] show a checkbox and say "All boxes will be shipped together, to a single location".  Default is checked.

- [ ] if "All boxes will be shipped together, to a single location" is checked, show shipping address selector using `SelectAddress` #16.  Else show text that says "Please go to your dashboard > Containers pending to ship to arrange box shipment, after confirming this Sales Order."

## TBC
add a box to let customer choose pick up immediately. if delivery order is generated.
