### ISSUE TITLE
UserProfileForm

### ISSUE THREAD

**Issue by screw123** [screw123/p001-frontend#23]
Showing User (not Account) info and for some fields allow users to edit.
Once user edit anything, submit button will be enabled and once pressed, send changes to backend.
Assume user is logined

## URL
./src/form/UserProfileForm.js

## Spec

- [x] On load, get user information from #24 GqlApi.state.myself and show on screen 

- [x] firstName and lastName is editable, email and mobilePhone are locked

- [x] password is editable, but to provide Existing Password and New Password field.  both will be needed to send to backend if need to change password

- [x] password need to be specially validated, for details, refer to `./src/form/SignUpForm.js`

- [x] for fields that are editable, show Formik-TextInput `src/component/Formik-TextInput.js` or whatever is appropriate

- [x] for fields that are locked, use disabled=true

- [x] check for isDirty of Formik form.  If isDirty, show submit button

- [x] on submit, run `updateUserDetails` #25  mutation using `GqlApi.getGqlClient()` #24 

- [x] after backend return from submit, use submit result to call `GqlApi.updateMyself()` #24 

- [x] after submit successful, if props.onSubmitSuccess is available, call the function with no arguments.

- [ ] send `existingPassword` to backend whenever there are changes.

**Comment by omiq17** [comment]
Spec#1: I have used componentDidMount() to get user info on load.
Spec#6: Instead of using plain text, I have used Field with readOnly parameter which restrict the user to change that field. Check if this idea seems good or not.
Spec#7,8: Check line no. 82-85

**Comment by screw123** [comment]
@omiq17 Looks fine for me, except that you copy the state of GqlApi.state.myself to this component.
The reason is:
UserProfileForm.state.user is copying the reference, not the value, because state.myself is an object, not a simple variable.

When GqlApi.state.myself changes, UserProfileForm's state will secretly changed as well (because it's referring to state of some other components).  And UserProfileForm won't even know, so the front-end won't be re-rendered.

What you should do is to create a warper component and provide `myself` as props, e.g:
const UserProfileForm = () => (<UserProfileFormInner user={GqlApi.state.myself()} /> )

class UserProfileFormInner extends React.Component {
  constructor(props) {
    super(props)
}

//refer to user by using props.user instead of this.state.user

}

**Comment by screw123** [comment]
Also did you already tested the code and can it function properly?

**Comment by omiq17** [comment]
Checked live with testpage. Called with a dummy object in TestPage.js 
Found out some frontend bugs when checking into website and fixed them. Although there need to clear about these options:  
- Now you have to provide both existing and new password.
- If any of editable field change, submit button gets enabled.

I haven't found ways to check backend! Go to testpage to check.

**Comment by screw123** [comment]
changed requirement for locked fields
also added requirement for onSubmitSuccess
